### ISSUE TITLE
Note Taking Workshop: Poster Creation

### ISSUE THREAD

**Issue by Josh-Abraham** [LassondePeerHelpers/2019-2020Planning#1]
Create a workshop poster that deatils the date time and location.

Date: Oct 3, 2019
Time: 1:30 - 2:30
Location: Bergeron Centre: Room 125

**Comment by mowhamadrexa** [comment]
The one that nobody liked:
![f2](https://user-images.githubusercontent.com/20386227/65400072-340ef200-dd8e-11e9-96be-05a007462a78.png)

**Comment by mowhamadrexa** [comment]
![f1](https://user-images.githubusercontent.com/20386227/65400209-ee9ef480-dd8e-11e9-8a33-b1daa78908fc.png)

**Comment by Josh-Abraham** [comment]
First one was a little difficult to read, second one looks good. Can you change it to Note-Taking & Group Work. Sorry, didn't notice it earlier

**Comment by Shogri** [comment]
Hi @mowhamadrexa , a few things:
- workshop name should be bigger than the details
- specify 1:30-2:30pm
- maybe include a short sentence or two about what the event is about
- The graphic is good, the font is also good but you have a lot of whitespace so you could maybe bold a few things

Looks good otherwise.

**Comment by mowhamadrexa** [comment]
![f1](https://user-images.githubusercontent.com/20386227/65448740-86d8c000-de07-11e9-951a-d8cfaa4274be.png)

**Comment by mowhamadrexa** [comment]
Slide:
![s1](https://user-images.githubusercontent.com/20386227/65449007-0feff700-de08-11e9-8dc0-28b07b3732cc.png)

**Comment by mowhamadrexa** [comment]
Slide v2
![s2](https://user-images.githubusercontent.com/20386227/65449207-783ed880-de08-11e9-9352-4cea7002ce3c.png)

**Comment by mowhamadrexa** [comment]
Slide V1.0.2
![s2](https://user-images.githubusercontent.com/20386227/65449258-94db1080-de08-11e9-9b81-7597e1867928.png)

**Comment by mowhamadrexa** [comment]
Slide V1.0.3:
![s3](https://user-images.githubusercontent.com/20386227/65449547-35313500-de09-11e9-8204-526eb3060766.png)

**Comment by mowhamadrexa** [comment]
Poster without Lassonde
![f3](https://user-images.githubusercontent.com/20386227/65561027-00a7a100-df0f-11e9-8099-f9f4c8331efc.png)

**Comment by Josh-Abraham** [comment]
Just for tracking purposes, the Lassonde logo needed to be removed because technically we are not Lassonde so can't advertise as such.
