### ISSUE TITLE
YASC Event

### ISSUE THREAD

**Issue by Josh-Abraham** [LassondePeerHelpers/2019-2020Planning#16]
Need volunteers for **November 29 from 2:30 to 3:30 pm**

**Comment by jpaglia** [comment]
YASC is requesting the following from the Peer Helper volunteers:
- Be available to be present from 2:30-3:30 pm on Friday, November 29
- Be willing to answer any questions from students regarding your university experience as well as study tips
- Provide the names of your professors for MATH 1013 and 1025

**Comment by neharikapuriyork** [comment]
Sounds Good !

**Comment by mowhamadrexa** [comment]
I'm available. Prof: Amenda Chow

**Comment by jpaglia** [comment]
Hi everyone, I was just informed that the YASC event has been rescheduled to **3:30** (instead of 2:30). I've sent a message on Slack so please let me know if this time still works for you - thanks

**Comment by neharikapuriyork** [comment]
Yes, am still available!

Best Regards,
Neharika Puri

Sent from Mail for Windows 10
