### ISSUE TITLE
Note Taking Workshop: Design Note Taking Content

### ISSUE THREAD

**Issue by Josh-Abraham** [LassondePeerHelpers/2019-2020Planning#2]
Create the content related to taking notes in class.
This will be a interactive component, that involves a "lecture" on note taking and someone demonstrating note taking skills in real time

**Comment by Josh-Abraham** [comment]
Docs link: https://docs.google.com/document/d/15wPcRlnPUej36UCOpXCro3BmRwTkOIrzueRn966k8lI/edit?usp=sharing

**Comment by yumstar** [comment]
[Note Taking Slides Summary.docx](https://github.com/LassondePeerHelpers/2019-2020Planning/files/3645017/Learning.Skills.Slides.Summary.docx)

**Comment by yumstar** [comment]
Script is completed. - Abu
(https://docs.google.com/document/d/15wPcRlnPUej36UCOpXCro3BmRwTkOIrzueRn966k8lI/edit?usp=sharing)

**Comment by A-Chidalu** [comment]
Filled in some of my parts.

**Comment by Josh-Abraham** [comment]
Ok looks good, task is being closed. Good job team :+1:
