### ISSUE TITLE
Note Taking Workshop: Design Note Style Guides

### ISSUE THREAD

**Issue by Josh-Abraham** [LassondePeerHelpers/2019-2020Planning#4]
Create style guides of good & bad note taking techniques based off of Peer Helper guides

**Comment by Josh-Abraham** [comment]
![002](https://user-images.githubusercontent.com/35229737/65381834-09a63180-dcc7-11e9-9e34-a5701bcb3bd7.jpg)

**Comment by yumstar** [comment]
![201909212331481000__01](https://user-images.githubusercontent.com/25469866/65381910-d95f9280-dcc8-11e9-9f2e-c6f1fad3def7.jpg)

**Comment by dinanauth** [comment]
![notestyle](https://user-images.githubusercontent.com/46362927/65395248-4ecd7080-dd66-11e9-86f9-390d7babfe52.jpg)

**Comment by A-Chidalu** [comment]
![GreatNotes1.JPG](https://images.zenhubusercontent.com/5d87ecc372f2c60001fac42b/55587355-3aa7-4f7e-8725-d8a2d5ad3ef5)![Greatnotes2.jpg](https://images.zenhubusercontent.com/5d87ecc372f2c60001fac42b/9844c769-1517-441f-b930-2bd6c1cc4b14)

**Comment by Josh-Abraham** [comment]
Moreka's
![Note taking Example](https://user-images.githubusercontent.com/35229737/65431383-639e1880-dde7-11e9-8ad3-0f721600e07a.jpg)

**Comment by Josh-Abraham** [comment]
Sheets have been printed, so this task is being closed. :+1:
