### ISSUE TITLE
Renaissance Cafe: Contact Club Reps to Attend

### ISSUE THREAD

**Issue by jpaglia** [LassondePeerHelpers/2019-2020Planning#6]
Contact the following clubs to ask if they are able to send representatives to the event on Oct. 10 from 12:30-2:30 pm:

![image](https://user-images.githubusercontent.com/33559206/65445130-8a684900-ddff-11e9-9822-bf46cc5501d3.png)

As clubs RSVP for the event (responding yes or no), please compile a doc with their responses. This document should be uploaded to this issue.

In addition, ask the clubs if they are looking for any external volunteers for their upcoming events and compile a list of these events.

**Comment by jpaglia** [comment]
Hi guys, I just wanted to get an update on the club reps attending on Oct. 10th. I reached out to YASC and they are able to send us a rep for the event, but we still need a lot more clubs.

Could you both please follow up with everyone (maybe split the list and each contact half the clubs) to remind them that we need confirmation ASAP - thanks.

**Comment by neharikapuriyork** [comment]
Hi,
I have contacted and reminded the clubs again. They didn't get back yet.  I
am still gonna continue reminding them.

Regards,
Neharika Puri

**Comment by jpaglia** [comment]
Hey guys, just a heads up with our event coming up on Thursday, we need to have responses from all clubs we've contacted by the end of day tomorrow - thanks!
