### ISSUE TITLE
Renaissance Cafe: Poster Creation

### ISSUE THREAD

**Issue by jpaglia** [LassondePeerHelpers/2019-2020Planning#7]
Create a poster following the guidelines outlined in the media document:
https://drive.google.com/drive/u/1/folders/1rf3y2PhYMabviCZGYRC5zgyfTKhCyScP

The event is booked for Thursday, October 10 from 12:30-2:30 pm in the Berg Eatery. It should also be advertised as BYOM (Bring Your Own Mug) for some fun ENG1101 selfies.

Please ensure that the posters meet the specs outlined in the doc and add screenshots to this issue for feedback.

**Comment by erick576** [comment]
![FaceBookCafePoster](https://user-images.githubusercontent.com/46385457/65563006-356b2680-df16-11e9-8b4f-c6908b49a69b.PNG)

**Comment by erick576** [comment]
![InstagramCafePoster](https://user-images.githubusercontent.com/46385457/65563743-972c9000-df18-11e9-90de-f10292f58a14.PNG)


Poster For Instagram Dimensions

**Comment by erick576** [comment]
![TvCafePoster](https://user-images.githubusercontent.com/46385457/65564354-a280bb00-df1a-11e9-967b-9124c3441c43.PNG)


Poster For Tv Dimensions

**Comment by jpaglia** [comment]
Hi @erick576 , just a few things:
- for tracking purposes, the Lassonde logo shouldn't be included because technically we are not Lassonde (so we can't advertise as such) - we only need the PH logo
- the text right now looks a little bit condensed, maybe play around with the spacing, sizing, and font colours to give it a softer feel
- the event doesn't need to be explicitly advertised as an ENG1101 selfie event because we'll be communicating that info to the profs already
- the _How To Get Involved_ event theme should be emphasized a bit more (maybe in the title section you can have "Renaissance Cafe" above the line and then "How To Get Involved" below the line?)

**_Side Note:_** It would also be interesting to see what this kind of poster would look like on a background with a funky mug (or mugs) to emphasize the _Bring Your Own Mug_ concept. This is also assuming you are able to find a good background image to match this suggestion. If not, we can stick to the background you're currently using.

Right now it looks like a good initial draft. We'll likely start advertising next Monday, so the rest of this week can be spent making any revisions as you finalize your next draft.

Also tagging @Shogri to take a look in case there was anything else I missed.

**Comment by Shogri** [comment]
@erick576 just to add a couple of things:

- We can't use the Lassonde logo
- for the Peer Helper logo, please give it a bit of cushioning space from the corner

If you could make these changes by tomorrow that would be great, that gives us time to give feedback and hopefully start advertising on Monday.

Thanks!

**Comment by jpaglia** [comment]
@Ballen-Alain-216341703 since Eric has already started working on the poster, I will be assigning you to make in-class advertisements. These will need to be done throughout next week in the following classes:

ENG1101 (Tuesday, Thursday 10:30 am - 12:30 pm)
- Jeff Harris > R  S137
- Reza Rizvi > LSB 106
- Kai Zhuang > DB  0016
- Amaneh Jadidi Mardkheh > CLH C

The announcement should only take a couple of minutes and should emphasize the event info, date, time, location, as well as the fact that the Renaissance Cafe is an experiential learning event. Also mention the fact that this is a Bring Your Own Mug event, to make it more fun. Please update this issue with a general outline/script for your announcement by tomorrow - thanks.

**Comment by Ballen-Alain-216341703** [comment]
Here is the general outline:
<img width="467" alt="Screen Shot 2019-09-27 at 2 42 25 PM" src="https://user-images.githubusercontent.com/46403906/65793950-10083380-e135-11e9-8a35-e69c07eaab39.png">

**Comment by Ballen-Alain-216341703** [comment]
I have a question, should I speak with the professors beforehand and let them know about the announcement?

**Comment by jpaglia** [comment]
@Ballen-Alain-216341703 yes, you should contact the profs in advance. Maybe split the 4 classes over the 2 days (2 on Tuesday and 2 on Thursday) just so you are not taking up too much of the class time.

**Comment by erick576** [comment]
Poster adjustments will be uploaded soon

**Comment by Ballen-Alain-216341703** [comment]
![TvCafePoster](https://user-images.githubusercontent.com/46403906/65808960-6b064e80-e166-11e9-8c07-0ff8576facae.PNG)
TV

**Comment by Ballen-Alain-216341703** [comment]
![InstagramCafePoster](https://user-images.githubusercontent.com/46403906/65808962-7194c600-e166-11e9-9b17-5e085b766084.PNG)
Instagram

**Comment by Ballen-Alain-216341703** [comment]
![FaceBookCafePoster](https://user-images.githubusercontent.com/46403906/65808966-76f21080-e166-11e9-9e21-e1e2d6825e94.PNG)
Facebook

**Comment by jpaglia** [comment]
@erick576 The text still looks very cluttered, maybe try using a font that isn't all in caps? Also, I think it still looks very heavy. Can you try changing the font colour to perhaps a dark brown so that the text fits better with the background?

Also, as previously mentioned we shouldn't be advertising this on the poster as a selfie event. The ENG1101 classes will get their own advertisements about that. In addition, "p.m." should be added to the event date and time details.

I also still think the _How To Get Involved_ event theme should be emphasized in the title section of the poster: e.g. The "Renaissance Cafe" title is above the line and then "How To Get Involved" below the line in a smaller font so that it fits.

Would it also be possible to look for a more fun background to emphasize the fact that the event is Bring Your Own Mug? - thanks

**Comment by erick576** [comment]
Ok I will play around with the fonts more and remove the selfie event (I originally thought you just wanted the ENG 1101 off).  I will also add the PM to the date and the "How to get involved". As for the background I did look however, I ended up sticking with this one because they weren't as spacious. to allow all the text to be comfortably placed.

**Comment by jpaglia** [comment]
@erick576 alright, thanks for looking into it. We can stick with this background then and just play around with the fonts instead

**Comment by Shogri** [comment]
@erick576 for reference if you want to use a busy background with text on top, you can always apply a %50-70 transparent white/black layer and add darker/lighter text on top (text doesn't necessarily have to be black and white)

**Comment by erick576** [comment]
Sure I will keep that in mind when playing with the fonts thanks

**Comment by erick576** [comment]
![FaceBookCafePoster](https://user-images.githubusercontent.com/46385457/65839948-62d21e80-e2e0-11e9-8826-939288307748.PNG)


So I tried to soften up the words and played around with the fonts and colors. Let me know if there is anything else you want me to change otherwise, I will begin making these adjustments on the other two posters. Thanks

**Comment by jpaglia** [comment]
I definitely think this font layout looks better. The brown does look a little bit green to me, though. Would it be possible to change that to a brown similar to the one shown below (#572d19) : 
![image](https://user-images.githubusercontent.com/33559206/65841418-037c0a80-e2f0-11e9-8444-b62e3fe1c72f.png)

Other than that, my only comment would be making the "How to get involved" line a little bit bigger and changing the second bullet point to something like "Snacks and drinks will be provided (so bring your own mug!)". The rest of it looks good - thanks for taking care of this!

**Comment by erick576** [comment]
![FaceBookCafePoster](https://user-images.githubusercontent.com/46385457/65842440-9cfbea00-e2f9-11e9-8a67-4988435fcb2f.PNG)

Facebook Poster

![InstagramCafePoster](https://user-images.githubusercontent.com/46385457/65842441-a38a6180-e2f9-11e9-9664-5f7b075d9ab7.PNG)

Instagram Poster


![TvCafePoster](https://user-images.githubusercontent.com/46385457/65842444-ab4a0600-e2f9-11e9-9bdd-1b425e34e7a7.PNG)


TV Poster

**Comment by erick576** [comment]
I tried to change the color as close to the shade you sent and adjusted the text. Let me know if there are anymore adjustments you need.

**Comment by Ballen-Alain-216341703** [comment]
I've contacted Kai Zhuang and Jeff Harris to do the advertisement on tuesday. Kai Zhuang responded and im still waiting on Jeff Harris. I'm planning to do Reza Rizvi and Amaneh Jadidi's class on thursday.

**Comment by jpaglia** [comment]
@erick576 The Instagram poster background looks a bit blurry because the image is too zoomed in. I think we will just use the TV poster as an Instagram advertisement. Can you please upload the original file to this issue so I can send it to Alicia? - thanks

@Ballen-Alain-216341703 Sounds good, if Jeff doesn't respond in time then I would start with his class first to ask in person before he begins teaching. Your script covers everything, so you should be fine to make the announcements. - thanks

**Comment by erick576** [comment]
Alright I uploaded the posters onto the drive

**Comment by jpaglia** [comment]
Thanks Eric, can you also upload the original editable file?

**Comment by Ballen-Alain-216341703** [comment]
[editable files.zip](https://github.com/LassondePeerHelpers/2019-2020Planning/files/3673442/editable.files.zip)
Here are the editable files without the text.

**Comment by Ballen-Alain-216341703** [comment]
![photo-1518966377293-74c63a1ec149](https://user-images.githubusercontent.com/46403906/65917370-33391a00-e3a5-11e9-9a0e-37365f90825d.jpeg)
This is the original photo.

**Comment by Ballen-Alain-216341703** [comment]
Hi Julia. The advertisement for Jeff and Kai's class is finished. For Thursday, is there anyone you can send out to deliver the presentation to one of the other classes. I find that delivering the announcements to the 2 classes at once would save some time.

**Comment by jpaglia** [comment]
@Ballen-Alain-216341703 Hi Alain, I have asked Brock to cover one of the classes. I'll get back to you once he responds.

**Comment by jpaglia** [comment]
@Ballen-Alain-216341703 unfortunately, Brock has a lab during that time. Would it be possible to make an announcement to one class at the beginning and then go to the other one at the end? Maybe that would be better for timing. Another option could be doing one class tomorrow and then going to the other one next Tuesday. You can decide whichever works best for you
